export const GET_USER_TOKEN_LIST_START = 'GET_USER_TOKEN_LIST_START';
export const GET_USER_TOKEN_LIST_SUCCESS = 'GET_USER_TOKEN_LIST_SUCCESS';
export const GET_USER_TOKEN_LIST_FAIL = 'GET_USER_TOKEN_LIST_FAIL';
